### ISSUE TITLE
Add ability to specify more than one clean transformation

### ISSUE THREAD

**Issue by timgentry** [PublicHealthEngland/ndr_import#13]
It should be possible to use an array of cleans as well as just one. Existing mappings like:

```
- column: ...
  mappings:
  - field: ...
    clean: :upcase
```
and arrays like:
```
- column: ...
  mappings:
  - field: ...
    clean:
    - :upcase
    - :strip
```
should both work.
