### ISSUE TITLE
Allow NdrImport::NonTabular::Table to trim raw text

### ISSUE THREAD

**Issue by timgentry** [PublicHealthEngland/ndr_import#21]
As a user
I want to be able to specify whether or not the raw text is trimmed (`left`, `right` or `both`)
So that when I capture a fixed input "area" e.g. `capture: !ruby/regexp /\A.{18}(.{13})/` trailing spaces can be removed, making identical comparisons easier and storage reduced.

Acceptance criteria:
A solution along the lines of the mapping below
```yaml
  non_tabular_cell:
    capture: !ruby/regexp /\A.{4}(.{13})/
    trim_rawtext: right
```
should capture "123" as the raw text, not "123&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;" when transforming "XXXX123&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NNN"
