### ISSUE TITLE
Preserve blank lines when joining lines in non-tabular data

### ISSUE THREAD

**Issue by ollietulloch** [publichealthengland/ndr_import#41]
**As an esourcemapper** I would like to be able to conditionally preserve blank lines when joining data together.

So that paragraphs/formatting can be maintained.

**It is done** when I can conditionally preserve blank lines within the `non_tabular_cell` in esourcemappings, eg:

```
  - column: textreport
    non_tabular_cell:
      lines: !ruby/object:RegexpRange
        begin: !ruby/regexp /\ASTART_OF_REPORT\z/
        end: !ruby/regexp /\AEND_OF_REPORT\z/
        excl: true
      capture: !ruby/regexp /\A(.*)\z/
      join: '\n'
      preserve_blank_lines: true
    mappings:
    - field: textreport
```
