### ISSUE TITLE
Efficient pre_map value substitution

### ISSUE THREAD

**Issue by timgentry** [PublicHealthEngland/ndr_import#8]
@joshpencheon raised the following question in a related pull request:

However, I wonder if we shouldn't implement `:pre_map` or something? Things like

``` yaml
replace:
- !ruby/regexp /\Aincoming\z/i: 'type_a'
- !ruby/regexp /\Aincoming_2\z/i: 'type_a'
- !ruby/regexp /\Aanother_incoming\z/i: 'type_b'
- !ruby/regexp /\Aanother_incoming_2\z/i: 'type_b'
```

, which are applied using `gsub!`, will be much less efficient than (something like):

``` yaml
pre_map:
  incoming: type_a
  incoming_2: type_a
  another_incoming: type_b
  another_incoming_2: type_b
```

and could be done with:

``` ruby
mapped_value = pre_map.fetch(mapped_value, mapped_value)
```
